### ISSUE TITLE
Textappender issues

### ISSUE THREAD

**Issue by OtakuFra** [MilitantHitchhiker/MilitantHitchhiker-SwitchbladePack#4]
![switchblade](https://github.com/user-attachments/assets/5143dc4e-8c06-4a6c-8759-7fa9dae0a747)
i don't know what's going on, if you need more details just tell me .

**Comment by MilitantHitchhiker** [comment]
Yeah, it's just started popping up, something in the latest ComfyUI update broke it. The only thing it could be is that they changed how they manage file write access. If you need a workaround for now you can use a Text Concat node from various packs to replicate the basic function.

**Comment by OtakuFra** [comment]
The problem is that the second red node (on the right) is not selectable, i can't even check its property. Anyway thx for the answer

**Comment by MilitantHitchhiker** [comment]
That's a comfyUI bug, if you click the small grey circle on the node header it will usually reactivate the node so you can get rid of it.
